# encoding: utf-8

# Init hooks
# Rango::Tasks.hook do
#   Dir["models/*.rb"].each(&method(:require))
# end

load "rango/tasks/bundle.thor"
load "pupu/tasks/pupu.thor"
load "rango/orm/adapters/datamapper/tasks.thor"

# add your tasks to the tasks directory and give them ".thor" suffix
