#!/bin/sh

echo "Entering pre-commit hook ..."

for file in $(git diff --staged --name-only); do
  echo "Normalizing $file ..."
  if test -f $file; then
    if ./script/normalize.rb "$file"; then
      git add $file # so the changes will be committed immediately
    fi
  fi
done
